[package]
name = "astrosim_cli"
version = "0.1.0"
authors = ["Arne Vansteenkiste <barnex@gmail.com>"]
edition = "2018"


[dependencies]
astrosim_lib = { path = "../astrosim_lib" }
csv = "1.1"
image = "0.23"
serde = { version = "1.0", features = ["derive"] }
structopt = "0.3"